update env vars

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -4,41 +4,60 @@ BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
 
+
+LUA_MAJOR=5.3
+LUA_VERSION=5.3.4
+LUA_MD5=53a9c68bcc0eda58bdc2095ad5cdfc63
+
+
+
+
 HAPROXY_MAJOR=1.8
 HAPROXY_VERSION=1.8.3
 HAPROXY_MD5=2e1e3eb42f07983c9303c5622d812862
 
-ARCHIVE=haproxy-${HAPROXY_VERSION}.tar.gz
-ARCHIVE_DIR=haproxy-${HAPROXY_VERSION}
+HAPROXY_ARCHIVE=haproxy-${HAPROXY_VERSION}.tar.gz
+HAPROXY_ARCHIVE_DIR=haproxy-${HAPROXY_VERSION}
 
 echo
 
 mkdir -p $CACHE_DIR
 
-if [ ! -e $CACHE_DIR/$ARCHIVE ]; then
-  echo "-----> Downloading ${ARCHIVE} from http://www.haproxy.org/..."
-  curl -sSL "http://www.haproxy.org/download/${HAPROXY_MAJOR}/src/haproxy-${HAPROXY_VERSION}.tar.gz" -o $CACHE_DIR/$ARCHIVE
+
+
+### START LUA
+#echo "-----> Downloading ${HAPROXY_ARCHIVE} from http://www.lua.org ..."
+#curl -sSL "http://www.lua.org/ftp/lua-5.3.4.tar.gz" -o "${CACHE_DIR}/lua-5.3.4.tar.gz"
+#echo "       Done"
+#tar -xzf "${CACHE_DIR}/lua-5.3.4.tar.gz" -C "${CACHE_DIR}/lua-5.3.4" --strip-components=1
+### END LUA
+
+
+
+if [ ! -e $CACHE_DIR/$HAPROXY_ARCHIVE ]; then
+  echo "-----> Downloading ${HAPROXY_ARCHIVE} from http://www.haproxy.org/..."
+  curl -sSL "http://www.haproxy.org/download/${HAPROXY_MAJOR}/src/haproxy-${HAPROXY_VERSION}.tar.gz" -o $CACHE_DIR/$HAPROXY_ARCHIVE
   echo "       Done"
 else
-  echo "-----> Using a locally cached copy of ${ARCHIVE}"
+  echo "-----> Using a locally cached copy of ${HAPROXY_ARCHIVE}"
 fi
 
-if ! (echo "${HAPROXY_MD5}  ${CACHE_DIR}/${ARCHIVE}" | md5sum -c --quiet); then
-  echo " !     Failed to verify authenticity of ${ARCHIVE} (should be ${HAPROXY_MD5})"
+if ! (echo "${HAPROXY_MD5}  ${CACHE_DIR}/${HAPROXY_ARCHIVE}" | md5sum -c --quiet); then
+  echo " !     Failed to verify authenticity of ${HAPROXY_ARCHIVE} (should be ${HAPROXY_MD5})"
   exit 1
 fi
 
-if [ ! -d $CACHE_DIR/$ARCHIVE_DIR ]; then
-  echo "-----> Unpacking ${ARCHIVE} to ${CACHE_DIR}/${ARCHIVE_DIR}"
-  mkdir -p "${CACHE_DIR}/${ARCHIVE_DIR}"
-  tar -xzf "${CACHE_DIR}/${ARCHIVE}" -C "${CACHE_DIR}/${ARCHIVE_DIR}" --strip-components=1
+if [ ! -d $CACHE_DIR/$HAPROXY_ARCHIVE_DIR ]; then
+  echo "-----> Unpacking ${HAPROXY_ARCHIVE} to ${CACHE_DIR}/${HAPROXY_ARCHIVE_DIR}"
+  mkdir -p "${CACHE_DIR}/${HAPROXY_ARCHIVE_DIR}"
+  tar -xzf "${CACHE_DIR}/${HAPROXY_ARCHIVE}" -C "${CACHE_DIR}/${HAPROXY_ARCHIVE_DIR}" --strip-components=1
   echo "       Done"
 fi
 
 echo
 echo "-----> Compiling..."
 
-make -sC "${CACHE_DIR}/${ARCHIVE_DIR}" \
+make -sC "${CACHE_DIR}/${HAPROXY_ARCHIVE_DIR}" \
 	TARGET=linux2628 \
 	USE_PCRE=1 PCREDIR= \
 	USE_OPENSSL=1 \
